# Generated by Django 3.0 on 2021-12-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='facebook',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='instagram',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='twitter',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
