# Generated by Django 3.2.6 on 2021-12-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydashboard', '0006_alter_businessprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='facebook',
            field=models.URLField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='instagram',
            field=models.URLField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='twitter',
            field=models.URLField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, default=' ', null=True),
        ),
    ]
