# Generated by Django 3.2.9 on 2021-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydashboard', '0007_auto_20211217_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
