# Generated by Django 3.2.9 on 2021-12-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydashboard', '0009_auto_20211221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='image',
            field=models.ImageField(blank=True, default='default2.png', null=True, upload_to='business_profiles/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
