# Generated by Django 3.2.9 on 2021-12-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catergory', '0004_alter_catergory_name'),
        ('companydashboard', '0010_auto_20211221_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='catergory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catergory.catergory'),
        ),
    ]
