# Generated by Django 3.2.9 on 2021-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergory', '0003_alter_catergory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
