# Generated by Django 3.2.9 on 2021-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
